apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-lfcg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-lfcg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-lfcg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-lfcg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-lfcg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uxov-tenant/rhtap-demo-app/hacbs-test-project-lfcg@sha256:7ff5bdb6a4eaa5364a798590f99dd684d29b2b9176ec6397e4667220addc5c6f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
